import test from 'node:test';
import assert from 'node:assert/strict';
import { rankCreditOrDebt } from './analysisRanking.ts';
import { recurringAnalysis } from './analysisRecurring.ts';
const req=(patch={})=>({domain:'debt',operation:'maximum',metric:'apr',purpose:'general',startDate:null,endDate:null,dateEvent:'none',entity:null,merchant:null,category:null,amount:null,...patch});
const snapshot=()=>({householdId:'h',today:'2026-09-10',capturedAt:'2026-09-10T15:00:00Z',timeZone:'America/Chicago',hash:'test',sources:Object.fromEntries(['bills','monthly_overrides','bill_date_moves','transactions','plaid_transactions','plaid_accounts'].map(t=>[t,{rows:[],complete:true}]))});
test('unknown debt balance is retained in known APR ranking with eligibility caveat',()=>{for(const balance of [null,undefined,' ']){const s=snapshot();s.sources.bills.rows=[{id:'known',name:'Known',is_debt:true,balance:100,interest_rate:10},{id:'unknown',name:'Unknown principal',is_debt:true,balance,interest_rate:35}];const r=rankCreditOrDebt(s,req());assert.equal(r.facts.rankedNames,'Unknown principal');assert.equal(r.facts.rankedValue,35);assert.equal(r.facts.rankedCount,2);assert.ok(r.missing.some(x=>/eligibility/.test(x)));assert.match(r.text,/not a complete-account ranking/);}});
test('unknown debt balance cannot disappear from balance-ranking completeness',()=>{const s=snapshot();s.sources.bills.rows=[{id:'known',name:'Known',is_debt:true,balance:100,interest_rate:10},{id:'unknown',name:'Unknown',is_debt:true,balance:null,interest_rate:35}];const r=rankCreditOrDebt(s,req({metric:'balance'}));assert.equal(r.facts.rankedNames,'Known');assert.ok(r.missing.length);});
test('known zero debt is excluded while incomplete scope still flagged',()=>{const s=snapshot();s.sources.bills.rows=[{id:'zero',name:'Paid',is_debt:true,balance:0,interest_rate:50},{id:'known',name:'Known',is_debt:true,balance:100,interest_rate:10}];const r=rankCreditOrDebt(s,req());assert.equal(r.facts.rankedNames,'Known');assert.deepEqual(r.missing,[]);s.sources.bills.complete=false;assert.ok(rankCreditOrDebt(s,req()).missing.length);});
function overdueSnapshot(unpaid=1){const s=snapshot();s.sources.bills.rows=Array.from({length:12+unpaid},(_,i)=>({id:`b${i}`,name:i<12?`Paid ${i}`:`OVERDUE ${i}`,amount:100,is_debt:false,is_recurring:true,frequency:'monthly',due_day:i+1,category:'Other',start_date:'2026-08-01',end_date:'2026-08-31',created_at:'2026-08-01T12:00:00Z'}));s.sources.monthly_overrides.rows=Array.from({length:12},(_,i)=>({id:`o${i}`,bill_id:`b${i}`,month:7,year:2026,paid_amount:100,actual_amount:100,paid_date:`2026-08-${String(i+1).padStart(2,'0')}`}));return s;}
test('overdue display filters paid rows before the twelve-item display limit',()=>{const r=recurringAnalysis(overdueSnapshot(),req({domain:'bills',purpose:'bills_overdue',operation:'summary',startDate:'2026-08-01',endDate:'2026-08-31'}));assert.deepEqual(r.missing,[]);assert.match(r.text,/OVERDUE 12/);assert.doesNotMatch(r.text,/Paid 0 —/);assert.equal(r.facts.occurrenceCount,13);assert.equal(r.facts.remainingObligations,100);assert.equal(r.facts.unpaidOccurrenceCount,1);assert.equal(r.facts.displayedOccurrenceCount,1);});
test('overdue cap retains complete unpaid totals and discloses omitted entries',()=>{const r=recurringAnalysis(overdueSnapshot(13),req({domain:'bills',purpose:'bills_overdue',operation:'summary',startDate:'2026-08-01',endDate:'2026-08-31'}));assert.equal(r.facts.unpaidOccurrenceCount,13);assert.equal(r.facts.remainingObligations,1300);assert.equal(r.facts.displayedOccurrenceCount,12);assert.match(r.text,/first 12 unpaid occurrences; totals cover all 13/);});

test('record creation cannot establish complete prior-month overdue coverage',()=>{
  const s=snapshot();s.sources.bills.rows=[{id:'b',name:'Existing rent',amount:900,is_debt:false,is_recurring:true,frequency:'monthly',due_day:1,category:'Other',start_date:null,end_date:null,created_at:'2026-09-09T12:00:00Z'}];
  const r=recurringAnalysis(s,req({domain:'bills',purpose:'bills_overdue',operation:'summary'}));
  assert.ok(r.missing.some(x=>/Record creation is not proof/.test(x)));assert.equal(r.facts.allRecordedDueSettled,undefined);
  const explicit=recurringAnalysis(s,req({domain:'bills',purpose:'bills_overdue',operation:'summary',startDate:'2026-08-01',endDate:'2026-08-31'}));
  assert.equal(explicit.facts.remainingObligations,900);assert.ok(explicit.missing.some(x=>/historical payment status/.test(x)));assert.equal(explicit.facts.allRecordedDueSettled,undefined);
  const allPaid=recurringAnalysis(s,req({domain:'bills',purpose:'bill_settlement',operation:'summary',startDate:'2026-08-01',endDate:'2026-08-31'}));
  assert.ok(allPaid.missing.length);assert.equal(allPaid.facts.allRecordedDueSettled,undefined);assert.doesNotMatch(allPaid.text,/^No—/);assert.match(allPaid.text,/not confirmation those bills were actually owed or unpaid/);
});
