import { Feather } from "@expo/vector-icons";
import React, { useMemo, useState } from "react";
import { Alert, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { DatePickerField } from "@/components/DatePickerField";
import { useBudget, type Bill, type DecisionRecord } from "@/context/BudgetContext";
import { useColors } from "@/hooks/useColors";
import { compareDecisionVariants, evaluateDecision, type DecisionScenario, type DecisionType } from "@/lib/decisions";

const TYPES: { id: DecisionType; label: string; icon: keyof typeof Feather.glyphMap }[] = [
  { id:"one_time_purchase",label:"Purchase",icon:"shopping-bag" }, { id:"recurring_bill",label:"New Bill",icon:"repeat" },
  { id:"income_change",label:"Income Change",icon:"trending-up" }, { id:"payment_date_change",label:"Move Bill Date",icon:"calendar" },
  { id:"savings_contribution",label:"Add to Savings",icon:"heart" }, { id:"extra_debt_payment",label:"Extra Debt",icon:"zap" },
];
const today = () => new Date().toISOString().slice(0,10);

export default function DecideScreen() {
  const c=useColors(), insets=useSafeAreaInsets();
  const { settings,bills,decisions,getDailyBalances,saveDecision,updateDecision,deleteDecision,addTransaction,deleteTransaction,addBill,deleteBill,addIncome,deleteIncome,setCustomDueDay,getCustomDueDay,previewDebtSnowball,applyDebtSnowballPayment,removeDebtSnowballPayment }=useBudget();
  const [type,setType]=useState<DecisionType>("one_time_purchase"),[name,setName]=useState(""),[amount,setAmount]=useState(""),[date,setDate]=useState(today()),[frequency,setFrequency]=useState<"once"|"weekly"|"biweekly"|"monthly">("once"),[sourceId,setSourceId]=useState("");
  const baseline=useMemo(()=>{ const start=new Date(); const out:{date:string;balance:number}[]=[]; for(let i=0;i<settings.forecast_horizon_months;i++){const m=(start.getMonth()+i)%12,y=start.getFullYear()+Math.floor((start.getMonth()+i)/12); getDailyBalances(m,y).forEach(d=>out.push({date:`${y}-${String(m+1).padStart(2,"0")}-${String(d.day).padStart(2,"0")}`,balance:d.balance}));} return out.filter(d=>d.date>=today()); },[getDailyBalances,settings.forecast_horizon_months]);
  const selectedBill=bills.find(b=>b.id===sourceId);
  const scenario=useMemo<DecisionScenario|null>(()=>{const value=Number(amount); if(!name.trim()||!Number.isFinite(value)||value===0||!date)return null; return {type,name:name.trim(),amount:value,date,frequency:(type==="recurring_bill"||type==="income_change")?frequency:"once",sourceId:sourceId||undefined,oldDate:selectedBill?`${date.slice(0,8)}${String(selectedBill.due_day).padStart(2,"0")}`:undefined};},[type,name,amount,date,frequency,sourceId,selectedBill]);
  const result=useMemo(()=>scenario&&baseline.length?evaluateDecision(baseline,scenario,settings.safety_floor):null,[baseline,scenario,settings.safety_floor]);
  const impact=useMemo(()=>{if(!scenario)return "";if(scenario.type==="payment_date_change")return selectedBill?`Moves ${selectedBill.name}; the monthly total stays unchanged.`:"Choose the bill whose date should move.";if(scenario.type==="extra_debt_payment"){const p=previewDebtSnowball(Number(scenario.date.slice(5,7))-1,Number(scenario.date.slice(0,4)),Math.abs(scenario.amount));return p.allocations[0]?`Targets ${p.allocations[0].billName}. Estimated debt-free date: ${p.debtFreeDate??"beyond projection"}.`:"No included snowball debt is available.";}if(scenario.type==="savings_contribution")return "Reduces available cash once and records the amount as savings activity.";if(scenario.type==="recurring_bill")return `Adds a ${scenario.frequency} obligation and reduces future flexible spending.`;if(scenario.type==="income_change")return `Changes future cash flow by ${scenario.amount>=0?"+":"−"}$${Math.abs(scenario.amount).toFixed(0)} per occurrence.`;return "Adds one planned expense; existing bills, goals, and debt payments remain scheduled.";},[scenario,selectedBill,previewDebtSnowball]);
  const comparisons=useMemo(()=>scenario?compareDecisionVariants(baseline,[.8,1,1.2].map(scale=>({...scenario,amount:Number((scenario.amount*scale).toFixed(2))})),settings.safety_floor):[],[baseline,scenario,settings.safety_floor]);
  const reset=()=>{setName("");setAmount("");setDate(today());setSourceId("");};
  const save=async(calendar=false)=>{if(!scenario||!result)return; await saveDecision(scenario,result,calendar?"calendar":"saved"); reset();};
  const undoApplied=async(a:Record<string,unknown>)=>{if(a.kind==="transaction"&&typeof a.id==="string")await deleteTransaction(a.id);else if(a.kind==="bill"&&typeof a.id==="string")await deleteBill(a.id);else if(a.kind==="income"&&typeof a.id==="string")await deleteIncome(a.id);else if(a.kind==="bill_date"&&typeof a.billId==="string")await setCustomDueDay(a.billId,Number(a.month),Number(a.year),typeof a.previous==="number"?a.previous:undefined);else if(a.kind==="debt")await removeDebtSnowballPayment(Number(a.month),Number(a.year));};
  const apply=async(decision?:DecisionRecord)=>{const s=decision?.scenario??scenario,r=decision?.result??result;if(!s||!r)return;if(r.verdict==="unsafe"){Alert.alert("Unsafe decision","Use the recommended safer amount or change the date first.");return;} let applied:Record<string,unknown>={};
    if(s.type==="one_time_purchase"||s.type==="savings_contribution") applied={kind:"transaction",id:await addTransaction({date:s.date,amount:-Math.abs(s.amount),category:s.type==="savings_contribution"?"Savings":"Other",note:s.name})};
    else if(s.type==="recurring_bill"|| (s.type==="income_change"&&s.amount<0)) applied={kind:"bill",id:await addBill({name:s.name,amount:Math.abs(s.amount),category:s.type==="income_change"?"Other":"Other",priority:1,is_debt:false,balance:0,interest_rate:0,due_day:Number(s.date.slice(8,10)),is_recurring:true,frequency:s.frequency==="weekly"?"weekly":"monthly"})};
    else if(s.type==="income_change") applied={kind:"income",id:await addIncome({name:s.name,amount:Math.abs(s.amount),frequency:s.frequency==="weekly"?"weekly":s.frequency==="biweekly"?"biweekly":"monthly",start_date:s.date,next_payment_date:s.frequency!=="monthly"?s.date:undefined})};
    else if(s.type==="payment_date_change"&&s.sourceId){const b=bills.find(x=>x.id===s.sourceId);if(b){const m=Number(s.date.slice(5,7))-1,y=Number(s.date.slice(0,4));const previous=getCustomDueDay(b.id,m,y);await setCustomDueDay(b.id,m,y,Number(s.date.slice(8,10)));applied={kind:"bill_date",billId:b.id,month:m,year:y,previous:previous??null};}}
    else if(s.type==="extra_debt_payment"){const debtMonth=Number(s.date.slice(5,7))-1,debtYear=Number(s.date.slice(0,4));const p=previewDebtSnowball(debtMonth,debtYear,Math.abs(s.amount));await applyDebtSnowballPayment(p);applied={kind:"debt",month:debtMonth,year:debtYear};}
    try {if(decision) await updateDecision({...decision,status:"applied",applied_change:applied}); else {const saved=await saveDecision(s,r,"applied");await updateDecision({...saved,applied_change:applied});reset();}} catch(error){await undoApplied(applied);Alert.alert("Decision not applied","The change was rolled back because it could not be saved.");throw error;}}
  const reverse=async(d:DecisionRecord)=>{await undoApplied(d.applied_change??{});await updateDecision({...d,status:"reversed"});};
  const verdictColor=result?.verdict==="safe"?c.success:result?.verdict==="caution"?"#d97706":c.destructive;
  return <ScrollView style={{backgroundColor:c.background}} contentContainerStyle={{paddingTop:Platform.OS==="web"?16:insets.top+16,paddingHorizontal:16,paddingBottom:110}} keyboardShouldPersistTaps="handled">
    <Text style={[s.title,{color:c.foreground}]}>Decide</Text><Text style={[s.sub,{color:c.mutedForeground}]}>Preview the tradeoff before changing your plan.</Text>
    <View style={s.typeGrid}>{TYPES.map(t=><Pressable key={t.id} onPress={()=>{setType(t.id);setFrequency(t.id==="recurring_bill"||t.id==="income_change"?"monthly":"once")}} style={[s.typeBtn,{backgroundColor:type===t.id?c.primary:c.card}]}><Feather name={t.icon} size={16} color={type===t.id?c.primaryForeground:c.primary}/><Text style={[s.typeText,{color:type===t.id?c.primaryForeground:c.foreground}]}>{t.label}</Text></Pressable>)}</View>
    <View style={[s.card,{backgroundColor:c.card}]}><TextInput style={[s.input,{backgroundColor:c.muted,color:c.foreground}]} placeholder="Decision name" placeholderTextColor={c.mutedForeground} value={name} onChangeText={setName}/><TextInput style={[s.input,{backgroundColor:c.muted,color:c.foreground}]} placeholder={type==="income_change"?"Monthly change (+ or -)":"Amount"} placeholderTextColor={c.mutedForeground} keyboardType="numbers-and-punctuation" value={amount} onChangeText={setAmount}/><DatePickerField label={type==="payment_date_change"?"New payment date":"Decision date"} value={date} onChange={setDate} placeholder="Choose date" />
      {(type==="recurring_bill"||type==="income_change")&&<View style={s.chips}>{(["weekly","biweekly","monthly"] as const).map(f=><Pressable key={f} onPress={()=>setFrequency(f)} style={[s.chip,{backgroundColor:frequency===f?c.primary:c.muted}]}><Text style={{color:frequency===f?c.primaryForeground:c.mutedForeground,textTransform:"capitalize"}}>{f}</Text></Pressable>)}</View>}
      {type==="payment_date_change"&&<View style={s.chips}>{bills.filter(b=>!b.is_debt).map((b:Bill)=><Pressable key={b.id} onPress={()=>{setSourceId(b.id);setName(`Move ${b.name}`);setAmount(String(b.amount))}} style={[s.chip,{backgroundColor:sourceId===b.id?c.primary:c.muted}]}><Text style={{color:sourceId===b.id?c.primaryForeground:c.mutedForeground}}>{b.name}</Text></Pressable>)}</View>}
      {result&&<><View style={[s.result,{borderColor:verdictColor}]}><Text style={[s.verdict,{color:verdictColor}]}>{result.verdict.toUpperCase()}</Text><Text style={[s.explain,{color:c.foreground}]}>{result.explanation}</Text><Text style={[s.detail,{color:c.mutedForeground}]}>Lowest ${result.lowestBalance.toFixed(0)} on {result.lowestBalanceDate} · {result.monthlyCashFlowChange>=0?"+":""}${result.monthlyCashFlowChange.toFixed(0)}/month</Text><Text style={[s.detail,{color:c.mutedForeground}]}>{impact}</Text>{result.verdict==="unsafe"&&<Text style={[s.detail,{color:c.primary}]}>Try ${result.saferAmount.toFixed(0)} or less.</Text>}</View><Text style={[s.section,{color:c.mutedForeground}]}>COMPARE AMOUNTS</Text><View style={s.compare}>{comparisons.map(x=><Pressable key={x.scenario.amount} onPress={()=>setAmount(String(x.scenario.amount))} style={[s.compareCard,{backgroundColor:c.muted}]}><Text style={[s.compareAmt,{color:c.foreground}]}>${x.scenario.amount.toFixed(0)}</Text><Text style={{color:x.result.verdict==="safe"?c.success:x.result.verdict==="caution"?"#d97706":c.destructive,fontSize:10,fontWeight:"700"}}>{x.result.verdict}</Text></Pressable>)}</View><View style={s.actions}><Pressable onPress={()=>void save(false)} style={[s.action,{backgroundColor:c.muted}]}><Text style={{color:c.foreground}}>Save</Text></Pressable><Pressable onPress={()=>void save(true)} style={[s.action,{backgroundColor:c.muted}]}><Text style={{color:c.foreground}}>Calendar</Text></Pressable><Pressable onPress={()=>void apply()} style={[s.action,{backgroundColor:c.primary}]}><Text style={{color:c.primaryForeground}}>Apply</Text></Pressable></View></>}
    </View>
    <Text style={[s.section,{color:c.mutedForeground}]}>DECISION HISTORY</Text>{decisions.map(d=><View key={d.id} style={[s.history,{backgroundColor:c.card}]}><View style={{flex:1}}><Text style={[s.historyName,{color:c.foreground}]}>{d.name}</Text><Text style={[s.detail,{color:c.mutedForeground}]}>{d.status} · {d.result.verdict} · ${Math.abs(d.scenario.amount).toFixed(0)} on {d.scenario.date}</Text></View>{(d.status==="saved"||d.status==="calendar")&&<Pressable onPress={()=>void apply(d)}><Text style={{color:c.primary,fontWeight:"700"}}>Apply</Text></Pressable>}{d.status==="applied"&&<Pressable onPress={()=>void reverse(d)}><Text style={{color:c.destructive,fontWeight:"700"}}>Reverse</Text></Pressable>}<Pressable onPress={()=>void deleteDecision(d.id)}><Feather name="trash-2" size={15} color={c.mutedForeground}/></Pressable></View>)}
  </ScrollView>;
}
const s=StyleSheet.create({title:{fontSize:28,fontFamily:"Inter_700Bold"},sub:{fontSize:13,marginTop:4,marginBottom:16},typeGrid:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:14},typeBtn:{width:"31%",padding:10,borderRadius:10,alignItems:"center",gap:5},typeText:{fontSize:11,fontFamily:"Inter_600SemiBold",textAlign:"center"},card:{padding:14,borderRadius:14},input:{height:46,borderRadius:10,paddingHorizontal:12,fontSize:15,marginBottom:10},chips:{flexDirection:"row",flexWrap:"wrap",gap:7,marginTop:8},chip:{paddingHorizontal:11,paddingVertical:8,borderRadius:8},result:{borderLeftWidth:4,padding:11,marginTop:14},verdict:{fontSize:13,fontFamily:"Inter_700Bold"},explain:{fontSize:14,fontFamily:"Inter_600SemiBold",marginTop:3},detail:{fontSize:11,marginTop:3},section:{fontSize:11,fontFamily:"Inter_700Bold",letterSpacing:.7,marginTop:18,marginBottom:8},compare:{flexDirection:"row",gap:8},compareCard:{flex:1,padding:10,borderRadius:9,alignItems:"center"},compareAmt:{fontSize:15,fontFamily:"Inter_700Bold"},actions:{flexDirection:"row",gap:8,marginTop:14},action:{flex:1,height:42,borderRadius:9,alignItems:"center",justifyContent:"center"},history:{flexDirection:"row",alignItems:"center",gap:12,padding:13,borderRadius:11,marginBottom:8},historyName:{fontSize:14,fontFamily:"Inter_700Bold"}});
