import { Feather } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React, { useMemo, useState } from "react";
import { Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useBudget } from "@/context/BudgetContext";
import { useBackDismiss } from "@/hooks/useBackDismiss";
import { useColors } from "@/hooks/useColors";

export function DecisionDueModal(){
  const c=useColors(),router=useRouter();
  const {decisions,goals,incomes,updateDecision,addTransaction,addBill,addIncome,updateIncome,updateGoal,previewDebtSnowball,applyDebtSnowballPayment}=useBudget();
  const now=new Date(),today=now.toISOString().slice(0,10);
  const [dismissedDueId,setDismissedDueId]=useState<string|null>(null);
  const due=useMemo(()=>decisions.find(d=>d.id!==dismissedDueId&&(d.status==="planned"||d.status==="calendar")&&(d.next_due_date??d.scenario.date)<=today&&(!d.remind_at||new Date(d.remind_at)<=now)),[decisions,dismissedDueId,today]);
  const [actual,setActual]=useState("");
  React.useEffect(()=>setActual(due?String(Math.abs(due.scenario.amount)):""),[due?.id]);
  const closeDue=()=>{if(due)setDismissedDueId(due.id)};
  useBackDismiss(Boolean(due), closeDue);
  if(!due)return null;
  const save=(patch:Partial<typeof due>)=>updateDecision({...due,...patch});
  const remind=()=>{const d=new Date();d.setDate(d.getDate()+1);void save({remind_at:d.toISOString()})};
  const postpone=()=>{const d=new Date(`${due.scenario.date}T00:00:00`);d.setDate(d.getDate()+7);const date=d.toISOString().slice(0,10);void save({scenario:{...due.scenario,date},next_due_date:date,calendar_date:date,remind_at:undefined})};
  const complete=async()=>{const amount=Math.max(0,Number(actual)||0),s=due.scenario;let applied:Record<string,unknown>={};
    if(s.type==="one_time_purchase"){applied={kind:"transaction",id:await addTransaction({date:today,amount:-amount,category:"Other",note:s.name})}}
    else if(s.type==="savings_contribution"){const goal=goals.find(g=>g.id===s.sourceId);if(goal)await updateGoal({...goal,current_amount:goal.current_amount+amount});applied={kind:"transaction",id:await addTransaction({date:today,amount:-amount,category:"Savings",note:s.name})}}
    else if(s.type==="recurring_bill"){const txId=await addTransaction({date:today,amount:-amount,category:"Other",note:s.name});const next=new Date(`${today}T12:00:00`);if(s.frequency==="weekly")next.setDate(next.getDate()+7);else if(s.frequency==="biweekly")next.setDate(next.getDate()+14);else{const targetDay=next.getDate();next.setDate(1);next.setMonth(next.getMonth()+1);next.setDate(Math.min(targetDay,new Date(next.getFullYear(),next.getMonth()+1,0).getDate()));}const billFrequency=s.frequency==="weekly"?"weekly":s.frequency==="biweekly"?"biweekly":"monthly";const billId=await addBill({name:s.name,amount,category:"Other",priority:1,is_debt:false,balance:0,interest_rate:0,due_day:next.getDate(),start_date:next.toISOString().slice(0,10),next_payment_date:next.toISOString().slice(0,10),is_recurring:true,frequency:billFrequency});applied={kind:"recurring",transactionId:txId,billId}}
    else if(s.type==="income_change"){const income=incomes.find(i=>i.id===s.sourceId);if(income){await updateIncome({...income,amount,amount_history:[...(income.amount_history??[]).filter(h=>h.effective_from!==today.slice(0,7)),{effective_from:today.slice(0,7),amount}]});applied={kind:"income_update",incomeId:income.id}}else applied={kind:"income",id:await addIncome({name:s.name,amount,frequency:s.frequency==="weekly"?"weekly":s.frequency==="biweekly"?"biweekly":"monthly",start_date:today,next_payment_date:s.frequency!=="monthly"?today:undefined})}}
    else if(s.type==="extra_debt_payment"){const p=previewDebtSnowball(now.getMonth(),now.getFullYear(),amount);await applyDebtSnowballPayment(p);applied={kind:"debt",month:now.getMonth(),year:now.getFullYear()}}
    await save({status:"completed",actual_amount:amount,completed_at:new Date().toISOString(),applied_change:applied,remind_at:undefined});
    const difference=Math.max(0,Math.abs(s.amount)-amount);if(difference>0&&(s.type==="one_time_purchase"||s.type==="recurring_bill")){const p=previewDebtSnowball(now.getMonth(),now.getFullYear(),difference,difference);if(p.allocations.length&&p.safeMaximum+0.005>=difference)Alert.alert("Under Plan",`You spent $${difference.toFixed(2)} less than planned. Add it to ${p.allocations[0].billName}?`,[{text:"Keep Available"},{text:"Add to Debt",onPress:()=>void applyDebtSnowballPayment(p)}]);}}
  return <Modal visible transparent animationType="slide" onRequestClose={closeDue}><View style={s.overlay}><View style={[s.sheet,{backgroundColor:c.card}]}><View style={[s.icon,{backgroundColor:c.primary+"18"}]}><Feather name="check-square" size={22} color={c.primary}/></View><Text style={[s.title,{color:c.foreground}]}>What happened with {due.name}?</Text><Text style={[s.sub,{color:c.mutedForeground}]}>Planned ${Math.abs(due.scenario.amount).toFixed(2)} for {due.scenario.date}</Text><Text style={[s.label,{color:c.mutedForeground}]}>Actual amount</Text><TextInput value={actual} onChangeText={setActual} keyboardType="decimal-pad" style={[s.input,{backgroundColor:c.muted,color:c.foreground}]}/><Pressable onPress={()=>void complete()} style={[s.primary,{backgroundColor:c.primary}]}><Text style={{color:c.primaryForeground,fontFamily:"Inter_700Bold"}}>Completed</Text></Pressable><View style={s.row}><Pressable onPress={()=>{const d=new Date();d.setDate(d.getDate()+1);void save({remind_at:d.toISOString()});router.push("/(tabs)/flo" as any)}} style={[s.secondary,{backgroundColor:c.muted}]}><Text style={{color:c.foreground}}>Changed</Text></Pressable><Pressable onPress={postpone} style={[s.secondary,{backgroundColor:c.muted}]}><Text style={{color:c.foreground}}>Postpone 7 days</Text></Pressable></View><View style={s.row}><Pressable onPress={remind} style={[s.secondary,{backgroundColor:c.muted}]}><Text style={{color:c.foreground}}>Remind tomorrow</Text></Pressable><Pressable onPress={()=>void save({status:"cancelled",remind_at:undefined})} style={[s.secondary,{backgroundColor:c.destructive+"15"}]}><Text style={{color:c.destructive}}>Cancel plan</Text></Pressable></View></View></View></Modal>
}
const s=StyleSheet.create({overlay:{flex:1,justifyContent:"flex-end",backgroundColor:"rgba(0,0,0,.6)"},sheet:{padding:22,borderTopLeftRadius:24,borderTopRightRadius:24},icon:{width:46,height:46,borderRadius:23,alignItems:"center",justifyContent:"center",marginBottom:12},title:{fontSize:20,fontFamily:"Inter_700Bold"},sub:{fontSize:13,marginTop:4},label:{fontSize:11,textTransform:"uppercase",marginTop:16,marginBottom:6},input:{height:48,borderRadius:10,paddingHorizontal:14,fontSize:17},primary:{height:48,borderRadius:10,alignItems:"center",justifyContent:"center",marginTop:14},row:{flexDirection:"row",gap:8,marginTop:8},secondary:{flex:1,height:42,borderRadius:9,alignItems:"center",justifyContent:"center"}});
