// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/flowledger-theme/BlueShift.tsx": () => import("../components/mockups/flowledger-theme/BlueShift.tsx"),
  "./components/mockups/flowledger-theme/GradientEdge.tsx": () => import("../components/mockups/flowledger-theme/GradientEdge.tsx")
};
